#!/bin/bash

if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "win32" ]]; then
    PATH_SEPARATOR=";"
else
    PATH_SEPARATOR=":"
fi

export PYTHONPATH="./$PATH_SEPARATOR../pmsat-inference$PATH_SEPARATOR../AALpy$PYTHONPATH"
echo "(unix) PYTHONPATH set to $PYTHONPATH"