#!/bin/bash

if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "win32" ]]; then
    PATH_SEPARATOR=";"
else
    PATH_SEPARATOR=":"
fi

export PYTHONPATH="../AALPY$PATH_SEPARATOR$PYTHONPATH"
echo "(unix) PYTHONPATH set to $PYTHONPATH"